#!/usr/bin/env python3

import skilstak.colors as c

def print_plain(name="Sam"):
    print("Hello " + name)

def print_sir(name="Sir"):
    print("Hello " + name)

if __name__ == '__main__':
    from sys import argv
    
    name = "Sir"
    option = ""

    if len(argv) == 1:
        print_plain(name)

    # hello -c
    # hello You

    if len(argv) == 2:
        if argv[1].startswith("-"):
            option = argv[1]
        else:
            name = argv[1]

    # hello -c You
    #???
