#!/usr/bin/env python3

import hellofunc as f
import skilstak.colors as c

if __name__ == '__main__':
    from sys import argv
    
    name = "Sir"
    option = " "

    if len(argv) == 1:
        f.print_plain(name)

    elif len(argv) == 2:
        if argv[1].startswith("-"):
            option = argv[1]
        else:
            name = argv[1]
    
    elif len(argv) == 3:
        option = argv[1]
        name = argv[2]

    if option == "-c":
        f.print_color(name)

    elif option == "-h":
        f.print_hello(name)
       
    elif option == "-m":
        f.print_multi(name)

    elif option == "-r":
        f.print_random(name)
